############################################################
#               data proceessor                            #
############################################################
- hosts: tag_Name_trainer_gen2_shallow03
  remote_user: ubuntu
  become: True

  vars:
    project_path: "{{ lookup('env','UMA_PROJECT_PATH') }}"

  roles:
    - trainer
